name: linux_system_info
description: Dart library for getting general linux system information like amount of ram or swap, cpu's MHz, cpu usage and kernel/distribution related data
version: 0.0.7
homepage: https://github.com/LolzDEV/linux_system_info

environment:
  sdk: '>=2.12.0 <3.0.0'


dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
dependencies:
  dbus: ^0.7.8
  ffi: ^2.0.1
  path: ^1.8.0
  tuple: ^2.0.0
  xdg_directories: ^0.2.0
  xml: ^6.2.2
