name: linux_system_info
description: Dart library for getting general linux system information like amount of ram or swap, cpu's MHz, cpu usage and kernel/distribution related data
version: 0.0.4
homepage: https://github.com/LolzDEV/linux_system_info

environment:
  sdk: '>=2.10.0 <3.0.0'


dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
dependencies:
  tuple: ^2.0.0
